services:
  cluttex:
    build:
      context: cluttex
  textlint-ja:
    build:
      context: textlint-ja
  tests:
    build:
      context: tests
    environment:
      HOST_PWD: $PWD
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: tests/
        target: /home/tests/
      - type: bind # pylintにrcファイルを読み込ませるため
        source: tests/pylintrc
        target: /home/pylintrc
      - type: bind
        source: data/
        target: /home/data/
    working_dir: /home
    entrypoint: ["python3"]
