name: 'Push images to container registry'

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  push_images:
    runs-on: ubuntu-latest
    name: 'Push Docker images'
    steps:
      - name: 'Checkoout repository'
        uses: actions/checkout@v3
      - name: 'Get the version from tag'
        run: echo '::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}'
        id: tag-version
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
      - name: 'Set the docker image tag'
        run: echo '::set-output name=tag::${TAG_VERSION:-latest}'
        id: docker-image-tag
        env:
          TAG_VERSION: ${{ steps.tag-version.outputs.VERSION }}
      - name: 'Print the tag-version'
        run: |
          echo "${{ steps.tag-version.outputs.VERSION }}"
          echo "${{ steps.docker-image-tag.outputs.tag }}"
      - name: 'Login to ghcr.io'
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u horatos --password-stdin
      - name: 'Build images'
        run: docker compose build
      - name: 'Push textlint-ja'
        run: |
          docker image ls
          docker tag docker-images-textlint-ja ghcr.io/horatos/textlint-ja:latest
          docker push ghcr.io/horatos/textlint-ja:${{ steps.docker-image-tag.outputs.tag }}
      - name: 'Push cluttex'
        run: |
          docker image ls
          docker tag docker-images-cluttex ghcr.io/horatos/cluttex:latest
          docker push ghcr.io/horatos/cluttex:${{ steps.docker-image-tag.outputs.tag }}
