name: 'Push images to container registry'

on:
  push:
  workflow_dispatch:

jobs:
  push_images:
    runs-on: ubuntu-latest
    name: 'Push Docker images'
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Login to ghcr.io'
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u horatos --password-stdin
      - name: 'Build and push textlint-ja'
        run: |
          docker compose build
          docker compose images
          #docker build -t textlint-ja textlint-ja
          #docker tag textlint-ja ghcr.io/horatos/textlint-ja:latest
          #docker push ghcr.io/horatos/textlint-ja:latest
