name: 'Push images to container registry'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_images:
    runs-on: ubuntu-latest
    name: 'Push Docker images'
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Login to ghcr.io'
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u horatos --password-stdin
      - name: 'Build images'
        run: docker compose build
      - name: 'Push textlint-ja'
        run: |
          docker tag docker-images_textlint-ja ghcr.io/horatos/textlint-ja:latest
          docker push ghcr.io/horatos/textlint-ja:latest
      - name: 'Push cluttex'
        run: |
          docker tag docker-images_cluttex ghcr.io/horatos/cluttex:latest
          docker push ghcr.io/horatos/cluttex:latest
